# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GelirGiderUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1189, 876)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 931, 531))
        self.groupBox.setObjectName("groupBox")
        self.tblVeriler = QtWidgets.QTableWidget(self.groupBox)
        self.tblVeriler.setGeometry(QtCore.QRect(370, 20, 551, 491))
        self.tblVeriler.setRowCount(100)
        self.tblVeriler.setColumnCount(5)
        self.tblVeriler.setObjectName("tblVeriler")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 342, 495))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.rdbtnGelir = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdbtnGelir.setFont(font)
        self.rdbtnGelir.setObjectName("rdbtnGelir")
        self.verticalLayout_2.addWidget(self.rdbtnGelir)
        self.rdbtnGider = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdbtnGider.setFont(font)
        self.rdbtnGider.setObjectName("rdbtnGider")
        self.verticalLayout_2.addWidget(self.rdbtnGider)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinMiktar = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinMiktar.setMaximum(999999)
        self.spinMiktar.setProperty("value", 0)
        self.spinMiktar.setObjectName("spinMiktar")
        self.horizontalLayout_2.addWidget(self.spinMiktar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lneAciklama = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneAciklama.setObjectName("lneAciklama")
        self.horizontalLayout_3.addWidget(self.lneAciklama)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.clndrTarih = QtWidgets.QCalendarWidget(self.layoutWidget)
        self.clndrTarih.setObjectName("clndrTarih")
        self.verticalLayout.addWidget(self.clndrTarih)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lblCuzdan = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblCuzdan.setFont(font)
        self.lblCuzdan.setText("")
        self.lblCuzdan.setObjectName("lblCuzdan")
        self.horizontalLayout_4.addWidget(self.lblCuzdan)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 590, 361, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 339, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.listwHazirGiderTipi = QtWidgets.QListWidget(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listwHazirGiderTipi.setFont(font)
        self.listwHazirGiderTipi.setObjectName("listwHazirGiderTipi")
        item = QtWidgets.QListWidgetItem()
        self.listwHazirGiderTipi.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listwHazirGiderTipi.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listwHazirGiderTipi.addItem(item)
        self.horizontalLayout_7.addWidget(self.listwHazirGiderTipi)
        self.btnHazirGiderEkle = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnHazirGiderEkle.setFont(font)
        self.btnHazirGiderEkle.setObjectName("btnHazirGiderEkle")
        self.horizontalLayout_7.addWidget(self.btnHazirGiderEkle)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 590, 314, 126))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnKaydet = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnKaydet.setFont(font)
        self.btnKaydet.setObjectName("btnKaydet")
        self.horizontalLayout_5.addWidget(self.btnKaydet)
        self.btnSil = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSil.setFont(font)
        self.btnSil.setObjectName("btnSil")
        self.horizontalLayout_5.addWidget(self.btnSil)
        self.btnListele = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnListele.setFont(font)
        self.btnListele.setObjectName("btnListele")
        self.horizontalLayout_5.addWidget(self.btnListele)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnCuzdanBelirle = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCuzdanBelirle.setFont(font)
        self.btnCuzdanBelirle.setObjectName("btnCuzdanBelirle")
        self.horizontalLayout_6.addWidget(self.btnCuzdanBelirle)
        self.lneCuzdanMiktari = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneCuzdanMiktari.setFont(font)
        self.lneCuzdanMiktari.setPlaceholderText("")
        self.lneCuzdanMiktari.setObjectName("lneCuzdanMiktari")
        self.horizontalLayout_6.addWidget(self.lneCuzdanMiktari)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.lblUyari = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblUyari.setFont(font)
        self.lblUyari.setText("")
        self.lblUyari.setObjectName("lblUyari")
        self.verticalLayout_4.addWidget(self.lblUyari)
        self.btnCikis = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCikis.setFont(font)
        self.btnCikis.setObjectName("btnCikis")
        self.verticalLayout_4.addWidget(self.btnCikis)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1189, 21))
        self.menubar.setObjectName("menubar")
        self.menuYard_m = QtWidgets.QMenu(self.menubar)
        self.menuYard_m.setObjectName("menuYard_m")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHakk_nda = QtWidgets.QAction(MainWindow)
        self.actionHakk_nda.setObjectName("actionHakk_nda")
        self.menuYard_m.addAction(self.actionHakk_nda)
        self.menubar.addAction(self.menuYard_m.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Gelir-Gider"))
        self.rdbtnGelir.setText(_translate("MainWindow", "GELİR"))
        self.rdbtnGider.setText(_translate("MainWindow", "GİDER"))
        self.label_2.setText(_translate("MainWindow", "Miktar:"))
        self.label_3.setText(_translate("MainWindow", "Nasıl Geldi/Gitti:"))
        self.label_4.setText(_translate("MainWindow", "Tarih:"))
        self.label_5.setText(_translate("MainWindow", "Cüzdan:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kayıtlı Giderler"))
        __sortingEnabled = self.listwHazirGiderTipi.isSortingEnabled()
        self.listwHazirGiderTipi.setSortingEnabled(False)
        item = self.listwHazirGiderTipi.item(0)
        item.setText(_translate("MainWindow", "1- NETFLİX - 40 TL"))
        item = self.listwHazirGiderTipi.item(1)
        item.setText(_translate("MainWindow", "2- SPOTİFY - 4.5 TL"))
        item = self.listwHazirGiderTipi.item(2)
        item.setText(_translate("MainWindow", "3- YOUTUBE - 16 TL"))
        self.listwHazirGiderTipi.setSortingEnabled(__sortingEnabled)
        self.btnHazirGiderEkle.setText(_translate("MainWindow", "EKLE"))
        self.btnKaydet.setText(_translate("MainWindow", "KAYDET"))
        self.btnSil.setText(_translate("MainWindow", "SİL"))
        self.btnListele.setText(_translate("MainWindow", "LİSTELE"))
        self.btnCuzdanBelirle.setText(_translate("MainWindow", "CÜZDAN BELİRLE"))
        self.lneCuzdanMiktari.setInputMask(_translate("MainWindow", "99999999999999999"))
        self.btnCikis.setText(_translate("MainWindow", "ÇIKIŞ"))
        self.menuYard_m.setTitle(_translate("MainWindow", "Yardım"))
        self.actionHakk_nda.setText(_translate("MainWindow", "Hakkında"))

