# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GirisEkrani.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(559, 412)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 10, 371, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lneKullaniciAdi = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneKullaniciAdi.setFont(font)
        self.lneKullaniciAdi.setObjectName("lneKullaniciAdi")
        self.verticalLayout.addWidget(self.lneKullaniciAdi)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lneSifre = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneSifre.setFont(font)
        self.lneSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneSifre.setObjectName("lneSifre")
        self.verticalLayout.addWidget(self.lneSifre)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lblBilgilendirme = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBilgilendirme.setFont(font)
        self.lblBilgilendirme.setText("")
        self.lblBilgilendirme.setObjectName("lblBilgilendirme")
        self.verticalLayout_2.addWidget(self.lblBilgilendirme)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnGirisYap = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGirisYap.setFont(font)
        self.btnGirisYap.setObjectName("btnGirisYap")
        self.horizontalLayout.addWidget(self.btnGirisYap)
        self.btnKayitOl = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnKayitOl.setFont(font)
        self.btnKayitOl.setObjectName("btnKayitOl")
        self.horizontalLayout.addWidget(self.btnKayitOl)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(360, 380, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kullanıcı Giriş Ekranı"))
        self.label.setText(_translate("Form", "Kullanıcı Adı:"))
        self.label_2.setText(_translate("Form", "Şifre:"))
        self.btnGirisYap.setText(_translate("Form", "Giriş Yap"))
        self.btnKayitOl.setText(_translate("Form", "Kayıt Ol"))
        self.label_3.setText(_translate("Form", "Designed by Simo Hayha"))

